add restore aof function and parse rdb at an offset
aliyun/redis-shake pull request #661
Opened 2023-08-27 13:13 UTC by bug-superman

add restore aof function and parse rdb at an offset

2023-08-27 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tair-opensource/RedisShake?pullRequest=661) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tair-opensource/RedisShake?pullRequest=661) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tair-opensource/RedisShake?pullRequest=661) it.</sub>

2023-08-28 07:11 UTC, suxb201 commented
Great job! Would you be willing to rebase your changes onto the v4 branch? We are currently working on the development of the v4 branch. You can refer to this documentation: https://tair-opensource.github.io/RedisShake/

2023-09-06 02:51 UTC, chenyang8094 commented
ref issue: #593

2023-09-12 03:37 UTC, bug-superman commented
有两问题:1.为什么在执行rdb恢复的时候没有检查文件完整性，例如rdb文件可以有crc64校验码，chensum。但我们并没有进行检查
2.现有的rdb是支持文件解析但不能进行offset返回。在使用rdb 混合aof格式时。无法使用现有的rdb解析代码完成，需要对此部分代码进行修改。
我们在发送之前做的检查我理解现在就是检查了命令是否存在。而不是针对文件进行校验和检查，是因为效率的原因么。读一遍文件做为检查的代价太大了不能接受么。

2023-09-12 03:52 UTC, bug-superman commented
> 干得好！您愿意将更改重构到v4分支上吗？我们目前正在开发v4分支。您可以参考此文档：https://tair-opensource.github.io/RedisShake/

cool  ！

2023-09-12 05:44 UTC, chenyang8094 commented
> 有两问题:1.为什么在执行rdb恢复的时候没有检查文件完整性，例如rdb文件可以有crc64校验码，chensum。但我们并没有进行检查 2.现有的rdb是支持文件解析但不能进行offset返回。在使用rdb 混合aof格式时。无法使用现有的rdb解析代码完成，需要对此部分代码进行修改。 我们在发送之前做的检查我理解现在就是检查了命令是否存在。而不是针对文件进行校验和检查，是因为效率的原因么。读一遍文件做为检查的代价太大了不能接受么。

我认为你可以不用考虑preamble格式，因为aof annotation和multi part aof都是在redis 7.0中release的，因此在7.0中，一旦开启preamble，那么只有base aof是rdb格式，incr aof依然是传统的resp格式。所以，你需要做的，就是支持multi part aof的增量文件按时间点闪回就好了。

2023-09-14 04:30 UTC, bug-superman commented
对于用户给的aof文件我们是否需要进行完整性检查，在写入前对文件的命令、格式进行check。目前代码似乎就是读取然后解析命令，然后写入，在解析途中遇到问题会报一个warnning。这是因为出于性能原因考虑吗，完整check一次文件太浪费时间？

2023-09-14 05:35 UTC, chenyang8094 commented
> 对于用户给的aof文件我们是否需要进行完整性检查，在写入前对文件的命令、格式进行check。目前代码似乎就是读取然后解析命令，然后写入，在解析途中遇到问题会报一个warnning。这是因为出于性能原因考虑吗，完整check一次文件太浪费时间？

可以暂时不考虑，因为aof没有rdb那样的checksum，想要校验的话只能从头捋一遍。

PITR时一般木标redis都是空实例，这个时候如果PITR中途失败了shake直接打印错误日志并退出就好，用户可以选择稍后flushall目标redis再使用正确的备份集重试PITR

2023-09-25 01:19 UTC, bug-superman commented
看v4版目前没有了fliter，是打算后续采用acl 命令来做吗

2023-09-25 02:19 UTC, suxb201 commented
> 看v4版目前没有了fliter，是打算后续采用acl 命令来做吗

这个：https://tair-opensource.github.io/RedisShake/zh/function/introduction.html

2023-09-25 06:51 UTC, chenyang8094 commented
@bug-superman 在PR顶部描述下你具体做了哪些改动，引入了什么功能、新增了什么配置、具体用法更新到使用文档（中文就好）。处理下test失败。

2023-10-07 01:42 UTC, chenyang8094 requested changes

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +}
下面空行

2023-10-07 01:42 UTC, chenyang8094 commented on tests/cases/aof.py
> +    opts = h.ShakeOpts.create_aof_opts(f"{src.dir}/appendonlydir/appendonly.aof.manifest", dst)
我没看到按照时间闪回的测试

2023-10-07 01:42 UTC, chenyang8094 commented on shake.toml
> +# [aof_reader]
新增配置前后都加一下空格

2023-10-07 01:42 UTC, chenyang8094 commented on shake.toml
> +# timestamp = 0
注释说明下时间戳的格式，单位是秒还是毫秒等

2023-10-07 01:42 UTC, chenyang8094 commented on docs/src/zh/guide/config.md
> +* [AOF Reader](../reader/aof_reader.md)
对应的英文版本文档的也要修改

2023-10-07 01:42 UTC, chenyang8094 commented on docs/src/zh/reader/aof_reader.md
> +aoffilepath="/tmp/appendonly.aof.manifest"
这里可以配置单个AOF（即非multi part aof）的路径？如果可以也加一下示例

2023-10-07 01:42 UTC, chenyang8094 commented on internal/aof/aof.go
> +					if ts > AOFTimeStamp && LastFile {
这里逻辑不对：闪回的意思是，从前往后load，依然遇到大于指定时间戳的数据，后面的数据都不需要了，无论当前这个aof是否是最后一个aof。

2023-10-07 01:42 UTC, chenyang8094 commented on internal/aof/aof.go
> +				//line, err := reader.ReadString('\n')
注释没用的话去掉

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +	//if am != nil {
为什么注释掉？

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +	manifestInfo.AOFManifest = AOFManifestcreate()
这里为什么要创建一个AOFManifest？理论上如果manifest不存在manifestInfo.AOFManifest应该为nil

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +func (manifestInfo *INFO) GetLastIncrAOFName(am *AOFManifest) string {
这些函数实现的目的是啥？理论上这都是Redis内部使用的,shake应该不会用到

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +func (manifestInfo *INFO) GetNewBaseFileNameAndMarkPreAsHistory(am *AOFManifest) string {
这个函数也是，都检查下，把无用的函数去掉

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/aof_reader.go
> +			log.Infof("the file stat:%v", fi)
如果是multi part aof，这里的stat应该是manifest的信息，打印出来没有什么意义

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/aof_reader.go
> +			log.Infof("start send AOF path=[%s]", r.path)
这里打印的日志最好能和上面的single aof有明显的区别，能明显区分到底是single aof还是multi part aof

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +			ret = manifestInfo.ParsingSingleAppendOnlyFile(AOFName, false, AOFTimeStamp)
base file是不是last file还不一定，这里不能直接标记为false

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +			ret = manifestInfo.ParsingSingleAppendOnlyFile(AOFName, false, AOFTimeStamp)
同时，因为base file（如果是aof格式）是rewrite生成的，所以里面的时间戳都是无效的（即不是真实写入时的时间戳），因此理论上base file里的数据都应该是无条件发送到对端的。时间戳应该只对增量文件有效。你check下base  aof里的timestamp是多少（如果是0那么这里就无需特殊处理）

2023-10-07 01:42 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +	StartLoading(totalSize, RDBFlagsAOFPreamble, 0)
没看到有调用对应的StopLoading

2023-10-17 06:26 UTC, chenyang8094 requested changes

2023-10-17 06:26 UTC, chenyang8094 commented on docs/src/zh/reader/aof_reader.md
> +aoffilepath="/tmp/appendonly.aof.manifest" "或者单aof文件 "/tmp/appendonly.aof""
最后多了一个引号

2023-10-17 06:26 UTC, chenyang8094 commented on docs/src/en/reader/aof_reader.md
> +aoffilepath="/tmp/appendonly.aof.manifest" "or single-aof: /tmp/appendonly.aof ""
最后多了一个引号

2023-10-17 06:26 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +			log.Panicf("This is an old version of the AOF File")
理论上，你当前的实现方案，是支持回放旧格式的AOF的，并且你也支持single aof文件，因此我认为这里可以把这个限制去掉

2023-10-17 06:26 UTC, chenyang8094 commented on internal/aof/aof.go
> +						log.Infof("AOFTruncated %s", line)
这里的日志打印的详细一点，说明这个截断的意思是因为到达了恢复时间点，后面的数据将不再读取

2023-10-17 06:26 UTC, chenyang8094 commented on shake.toml
> +# timestamp = 0              # Unix timestamp (millisecond level)
AOF中的timestamp annotation是秒级，这里使用毫秒级看上去没必要

2023-10-17 06:26 UTC, chenyang8094 commented on tests/appendonlydir/appendonly.aof.1.incr.aof
> +$6
你这里准备的文件有点太简单了，你至少要有多个增量文件，比如可以先把aof-disable-auto-gc关掉，这样将会有多个history文件。

即测试中需要模拟如下场景：
1、只有base file
2、base + incr file
3、base + hsitory + inrc file
4、only single aof (这个aof可以是redis 7.0的也可以是任意合法的aof)

2023-10-17 06:26 UTC, chenyang8094 commented on internal/reader/parsing_aof.go
> +				log.Infof("DB loaded from incr File %v: %.3f seconds", AOFName, float64(Ustime()-start)/1000000)
如果返回了AOFTruncated应该不用继续加载剩余的文件了吧

2023-10-17 06:27 UTC, chenyang8094 commented
@suxb201 你可以看下这个PR还有没有其他的问题。

2023-10-22 16:26 UTC, bug-superman commented on tests/appendonlydir/appendonly.aof.1.incr.aof
> +$6
只有base file不知道怎么模拟。
base + hsitory + inrc file 已经增加到测试case中，其他两个之前已经在现有测试中

2023-10-30 01:29 UTC, chenyang8094 requested changes

2023-10-30 01:29 UTC, chenyang8094 commented on tests/cases/aof.py
> +    create_aof_dir(current_directory + + "/appendonlydir")
```suggestion
    create_aof_dir(current_directory + "/appendonlydir")
```

2023-10-30 01:55 UTC, chenyang8094 approved these changes
LGTM

2023-10-30 02:02 UTC, suxb201 requested changes

2023-10-30 02:02 UTC, suxb201 commented on docs/src/en/reader/aof_reader.md
> +aoffilepath="/tmp/appendonly.aof.manifest" "or single-aof: /tmp/appendonly.aof"
不符合 toml 语法。

2023-10-30 12:11 UTC, suxb201 approved these changes
LGTM

2023-10-30 12:21 UTC, merged

2023-10-30 12:36 UTC, suxb201 commented
🎉

2024-08-02 03:03 UTC, Exile-Twilight commented
![image](https://github.com/user-attachments/assets/8c0119a3-9c85-4930-8a38-f3a8ddb19cc6)
请问解析aof过程中出于什么考虑限制了命令中参数的个数，Redis好像没有这方面的限制

2024-08-02 03:05 UTC, suxb201 commented
@Exile-Twilight 是的，不应该限制。

2025-05-21 07:12 UTC, Ryu-Z commented
目前是不是还有相关问题呀, 使用aof文件恢复直接报错

2025-05-21 07:14 UTC, suxb201 commented
@Ryu-Z 如果能帮着改改最好，非常感谢。列一下单开个 Issue也行。但我近期没精力修 aof 这块的 bug 了。