add feature about perfer connect to replica node
aliyun/redis-shake pull request #725
Opened 2023-12-13 09:12 UTC by jjz921024

for #724

2023-12-26 09:22 UTC, jjz921024 commented
rebase onto HEAD

2023-12-26 12:45 UTC, suxb201 requested changes

2023-12-26 12:45 UTC, suxb201 commented on internal/reader/scan_standalone_reader.go
> +	PerferReplica bool   `mapstructure:"perfer_replica" default:"true"`
建议默认是 false，从用户角度来看 shake 默认就是连接到主节点的。

2023-12-26 12:45 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> +	PerferReplica bool   `mapstructure:"perfer_replica" default:"true"`
同上，false

2023-12-26 12:45 UTC, suxb201 commented on shake.toml
> +# prefer_replica = true      # set to true if you want to sync from replica node
false，同上。

2023-12-26 12:45 UTC, suxb201 commented on shake.toml
> +prefer_replica = true # set to true if you want to sync from replica node
false，同上。

2023-12-26 12:45 UTC, suxb201 commented on internal/utils/cluster_nodes.go
> +				addresses = append(addresses, replicaAddr[0])
master 和 replicas 是 map 类型，对 map 做 range 操作的顺序是不确定的吧。
这个函数返回 addresses 与 slots，要求 addresses 的顺序和 slots 顺序是对应的，如果不对应会导致集群的写入出现问题。

2023-12-27 02:28 UTC, jjz921024 commented on internal/reader/scan_standalone_reader.go
> +	PerferReplica bool   `mapstructure:"perfer_replica" default:"true"`
update

2023-12-27 02:32 UTC, jjz921024 commented on internal/utils/cluster_nodes.go
> +				addresses = append(addresses, replicaAddr[0])
是的，我修改了这里取地址的逻辑，大致是 解析slot时保存nodeId，解析完所有信息后，按nodeId检索map中的address。请帮忙review

2023-12-27 03:48 UTC, suxb201 approved these changes

2023-12-27 03:48 UTC, merged