support gracefully shutdown
aliyun/redis-shake pull request #728
Opened 2023-12-14 09:15 UTC by jjz921024

for #727 

Modifications:
1. make a channel to receive quit signal
2. add a atomic `IsClosed` indacate the reader should be close
3. check `IsClosed` at the loop of  `SyncReader` and `ScanReader`

2023-12-21 13:27 UTC, Zheaoli requested changes
以及建议格式化一下代码

2023-12-21 13:27 UTC, Zheaoli commented on internal/reader/parsing_aof.go
> +		ldRDB.StartRead(context.TODO())
这里尽量不要用 `context.TODO`

2023-12-21 13:27 UTC, Zheaoli commented on internal/reader/scan_standalone_reader.go
> +	isStop atomic.Bool
这里为什么要用这个？

2023-12-21 13:27 UTC, Zheaoli commented on internal/reader/scan_standalone_reader.go
> +		for !r.isStop.Load() {
尽量不要用这样的方式
可以在 for 循环里用 select 来解决

2023-12-21 13:27 UTC, Zheaoli commented on internal/reader/sync_standalone_reader.go
> +	for !r.isStop.Load() {
同上

2023-12-21 13:55 UTC, jjz921024 commented on internal/reader/scan_standalone_reader.go
> +		for !r.isStop.Load() {
是指这样吗？
```
for {
    select {
    case <-ch:
        goto Label
    default:
        // do something...
     }
 }
Label:
```
因为break不会跳出for循环，感觉golang这里设计的挺让人难受的，就没这么用...

2023-12-21 14:58 UTC, Zheaoli commented on internal/reader/scan_standalone_reader.go
> +		for !r.isStop.Load() {
因为你这里没有剩下的逻辑，你 case <- ctx.Done 之后，直接进入 Close 逻辑，然后 Return 就行，不需要额外的处理

2023-12-21 14:59 UTC, Zheaoli commented on internal/reader/scan_standalone_reader.go
> +		for !r.isStop.Load() {
这里的问题是如果你每次 for loop 都来 atomic Load 然后比较，会额外吃很多 CPU

2023-12-22 01:59 UTC, jjz921024 commented on internal/reader/scan_standalone_reader.go
> +		for !r.isStop.Load() {
明白了，我修改一下，谢谢~

2023-12-22 02:47 UTC, jjz921024 commented
@Zheaoli I have fixed it, please check

2023-12-22 13:33 UTC, Zheaoli approved these changes
LGTM cc @suxb201

2023-12-22 19:04 UTC, Zheaoli commented
测试挂了，得看下为什么

2023-12-25 01:55 UTC, jjz921024 commented
> 测试挂了，得看下为什么

看了下日志，应该是CI的问题？

2023-12-25 02:10 UTC, suxb201 commented
我来修复下。

2023-12-25 02:34 UTC, suxb201 commented
@jjz921024 CI 修复了，需要你 rebase 代码再试一下。

2023-12-25 03:10 UTC, jjz921024 commented
> @jjz921024 CI 修复了，需要你 rebase 代码再试一下。

@suxb201 rebase了

2023-12-25 03:38 UTC, suxb201 commented
@jjz921024 还是有问题，我晚些看下。

2023-12-25 11:05 UTC, suxb201 requested changes

2023-12-25 11:05 UTC, suxb201 commented on internal/aof/aof.go
>  					break
这里的 break 只会跳出当前 select，不会终止外层的 for，与期望不符合。
aof_reader 预期的行为是处理完所有的 aof 文件后自行停止程序，不是等待外部发送信号。

2023-12-25 11:05 UTC, suxb201 commented on internal/aof/aof.go
>  					break
修改为 return ret 可以解决 CI 问题。

2023-12-25 11:15 UTC, jjz921024 commented on internal/aof/aof.go
>  					break
好的，没注意到这里，我修改一下，谢谢~

2023-12-26 02:51 UTC, suxb201 commented
@jjz921024 辛苦
1. 麻烦解决下冲突
2. 麻烦合并下 9bb89854607d8c901fc085365c608ba730c2aa71，尽量使用语意化的 commit msg：https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

2023-12-26 06:32 UTC, suxb201 approved these changes

2023-12-26 06:32 UTC, merged