bugfix: sync reader adaptive gracefully shutdown
aliyun/redis-shake pull request #760
Opened 2024-01-17 03:01 UTC by zgg2001

之前的sync读部分新增了优雅退出部分，但是存在一些缺陷，具体如下：

复现流程一：
1. sync模式配置开启RDB同步、关闭AOF同步
2. 在某个协程RDB同步完成时，会直接关闭reader client，导致协程里读到关闭的连接引发panic。

复现流程二：
1. sync模式配置开启RDB同步
2. 发送信号触发优雅退出，会直接关闭reader client，导致协程里读到关闭的连接引发panic。

由于集群模式下是多协程同步，一个协程引发panic会导致其余协程存在数据同步不完全的问题，需要修复一下。

2024-01-17 03:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/tair-opensource/RedisShake?pullRequest=760) <br/>All committers have signed the CLA.

2024-01-17 03:04 UTC, zgg2001 commented
由于避免一些Redis异常场景导致wait()长时间阻塞，我添加设置了10秒超时时间，麻烦一起评估下相关的更改

2024-01-19 01:56 UTC, suxb201 commented
我猜测问题原因是 reader 对象已经被析构了，但是对应的两个协程没有及时析构，访问不存在的对象。
或许这样修复就可以解决问题：
```golang
    go func() {
        r.sendReplconfAck()
    }()
```
使用闭包避免 r 被提前释放。receiveAOF 同理。

2024-01-19 01:58 UTC, suxb201 requested changes

2024-01-19 01:58 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> +		readerStopDone := make(chan struct{})
我认为这些 chan 是冗余的，当前已经有 Context 了。需要做的是使用闭包让 Reader 对象的生命周期长于协程的生命周期。

2024-01-19 02:19 UTC, zgg2001 commented on internal/reader/sync_standalone_reader.go
> -		r.client.Close()
@suxb201 核心应该是之前新增优雅推出功能时，在StartRead()里添加了这行
```golang
r.client.Close()
```
这里释放连接导致上方协程panic，所以我认为此处单纯通过闭包管理可能无法达到预期。

2024-01-19 02:24 UTC, zgg2001 commented on internal/reader/sync_standalone_reader.go
> +		readerStopDone := make(chan struct{})
现在我觉得可以考虑两种方式
1. 通过操作系统或最终析构来关闭连接，不额外添加代码手动关闭连接
2. 通过我实现的这种方式，优雅关闭连接
3. 考虑通过context，优雅关闭连接

2024-01-19 02:24 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> -		r.client.Close()
确实有这个问题，我们可以删去这一行，你感觉这里不主动关闭 client 是合适的写法吗？毕竟 GC 的时候也会关闭连接，我感觉可以。

2024-01-19 02:30 UTC, zgg2001 commented on internal/reader/sync_standalone_reader.go
> -		r.client.Close()
> 确实有这个问题，我们可以删去这一行，你感觉这里不主动关闭 client 是合适的写法吗？毕竟 GC 的时候也会关闭连接，我感觉可以。

我觉得合理，正常需要关闭reader连接的时候，也是程序结束的时候。

2024-01-19 02:39 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> +		readerStopDone := make(chan struct{})
倾向于 1+3。

----

context 目前是有的。
在你的修改中，执行顺序是：
1. 等待其余协程退出
2. close client
3. context 关闭
在其中 context 没有起作用。

2024-01-19 02:39 UTC, zgg2001 commented
@suxb201 已调整，申请合入

2024-01-19 02:50 UTC, zgg2001 commented on internal/reader/sync_standalone_reader.go
> +		readerStopDone := make(chan struct{})
> 倾向于 1+3。
> 
> context 目前是有的。 在你的修改中，执行顺序是：
> 
> 1. 等待其余协程退出
> 2. close client
> 3. context 关闭
>    在其中 context 没有起作用。

1就是直接删除此处的close操作，后续context会保证优雅退出，故此处直接删除close操作即可。

2024-01-19 02:58 UTC, suxb201 approved these changes

2024-01-19 03:16 UTC, merged

2024-02-04 03:15 UTC, jjz921024 commented on internal/reader/sync_standalone_reader.go
> -		r.client.Close()
这个问题我后面也发现了，这里资源释放的顺序有问题，应该 `close(r.ch)` 在最后执行，以保证其他资源可以被释放。抱歉引入这个bug