添加动态识别库号
aliyun/redis-shake pull request #782
Opened 2024-03-19 01:29 UTC by blight19

添加动态识别库号，兼容云上库号没有16个库带限制

2024-03-20 06:57 UTC, suxb201 requested changes

2024-03-20 06:57 UTC, suxb201 commented on internal/client/redis.go
> +func (r *Redis) Scan(cursor uint64, batch string) (newCursor uint64, keys []string) {
建议使用 count int，语义更明确。

2024-03-20 06:57 UTC, suxb201 commented on internal/reader/scan_standalone_reader.go
> +		batch := strconv.Itoa(r.opts.Batch)
同样，batch 建议改为 count，使用和 Redis 一样的命名：https://redis.io/commands/scan/

2024-03-20 07:40 UTC, blight19 commented on internal/client/redis.go
> +func (r *Redis) Scan(cursor uint64, batch string) (newCursor uint64, keys []string) {
这里使用int的话就多了一次类型转换，或者将下面的Redis.Send方法也修改为...interface

2024-03-20 07:43 UTC, suxb201 commented on internal/client/redis.go
> +func (r *Redis) Scan(cursor uint64, batch string) (newCursor uint64, keys []string) {
极小的开销，不需要担心。

2024-03-20 08:00 UTC, blight19 commented on internal/client/redis.go
> +func (r *Redis) Scan(cursor uint64, batch string) (newCursor uint64, keys []string) {
统一了下都弄成interface{},和下游匹配了，也不用int和string来回转换

2024-03-22 02:17 UTC, suxb201 approved these changes

2024-03-22 02:19 UTC, merged