Optimize: bytes.Index and humanize.IBytes in SyncStandaloneReader
aliyun/redis-shake pull request #909
Opened 2024-12-25 04:01 UTC by cyningsun

Opt:
1. Replace bytes.Index with bytes.Equal between lastBytes and `EOF MARKER`
2. Move humanize from every write to stats print

Before:
![image](https://github.com/user-attachments/assets/52de5824-c073-4a46-9522-413fc790e544)

After:
![image](https://github.com/user-attachments/assets/9c980e1c-5111-4f27-ae7b-c8081b5744f1)

2024-12-25 08:09 UTC, EquentR commented
Here's a question: Will doing this make the status interface unable to retrieve the humanized result? What if I want to view the status?

2024-12-25 08:25 UTC, cyningsun commented
Currently Interface Statusable retrieve the humanized result only by method `StatusString()`. And `StatusString` can convert those stats to humanized result when called instead of calculated those stats to humanized result after every writing to rdb

2024-12-25 08:29 UTC, EquentR commented
> Currently Interface `Statusable` retrieve the humanized result only by method `StatusString()`. And `StatusString` can convert those stats to humanized result when called instead of calculated those stats to humanized result after every writing to rdb

No no, you look at the `Statusable` interface, in the json result obtained using the web interface, the `Status` func is used to generate json result!

2024-12-25 08:33 UTC, EquentR commented
![image](https://github.com/user-attachments/assets/91da5cb1-f202-4abe-9a99-bfd24c39bb8e)

2024-12-25 08:33 UTC, cyningsun commented
sure. Will check and fix it.

2024-12-26 03:21 UTC, cyningsun commented
@EquentR Issue resolved.

2024-12-26 03:29 UTC, EquentR commented
@suxb201 看一下，好像是能提高一点点性能的样子

2024-12-26 09:09 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> +func (s syncStandaloneReaderStat) MarshalJSON() ([]byte, error) {
是不是可以在 syncStandaloneReaderStat 中保留 *Human 字段
在 MarshalJSON 中改成如下：
1. 更新 *Human 字段
2. 调用 json.Marshal
我理解这样比塞字段进去要好理解且代码量低一些

2024-12-26 09:49 UTC, suxb201 requested changes

2024-12-26 09:49 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> -		if bytes.Contains(buffer, bMarker) {
这里会不会有 BUG，比如收到一半 Marker。

2024-12-26 09:49 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> +		if lastBytes != nil { // add previous tail
好像不需要判断，空也可以复制

2024-12-26 09:49 UTC, suxb201 commented on internal/reader/sync_standalone_reader.go
> -			if len(buffer[fi+40:]) > 0 {
剩下的 byte 需要 aof 来处理.... 这个 BUG 不好修

2024-12-27 02:48 UTC, cyningsun commented on internal/reader/sync_standalone_reader.go
> -			if len(buffer[fi+40:]) > 0 {
如果在 redis-shake 发送 REPLCONF ACK <replication_offset> 给 Redis，确认 RDB 接收完毕之前，不开始 AOF 发送应该就不会有问题。具体还没看到这么细节。

2024-12-27 02:49 UTC, cyningsun commented on internal/reader/sync_standalone_reader.go
> -		if bytes.Contains(buffer, bMarker) {
如果一部分数据已被写入文件会有问题

2024-12-30 02:00 UTC, suxb201 approved these changes
你是正确的

            /* If this was a diskless replication, we need to really put
             * the slave online when the first ACK is received (which
             * confirms slave is online and ready to get more data). */
            if (c->repl_put_online_on_ack && c->replstate == SLAVE_STATE_ONLINE)
                putSlaveOnline(c);

2025-01-14 07:54 UTC, suxb201 approved these changes

2025-01-14 07:54 UTC, merged